# Ansible >2 deploy playbook
# use: ansible-playbook -i 192.168.0.1, deploy-service.yml
# LOOK AT COMMA, IT IS IMPORTANT     ^^^
# or as usual: ansible-playbook -i hosts.list deploy-service.yml

---
- hosts: all
  remote_user: root
  become_user: root
  become: yes
  tasks:
    - name: install system requiremets
      dnf: name={{item}} state=latest disable_gpg_check=yes
      with_items:
        - yum-utils
        - wget
    - name: copy mono repo
      copy:
        src=files/download.mono-project.com_repo_centos_.repo
        dest=/etc/yum.repos.d/download.mono-project.com_repo_centos_.repo
        force=yes
    - name: install system requiremets
      dnf: name={{item}} state=latest disable_gpg_check=yes
      with_items:
        - mono-core
        - mono-extras
    - name: add user
      user: name=bluemesh shell=/sbin/nologin
    - name: set permissions
      file: path=/home/bluemesh owner=bluemesh group=bluemesh mode=0700
    - name: download bluemesh binary
      command: chdir=/home/bluemesh sudo -u bluemesh {{item}}
      with_items:
        - wget http://dqteam.org/public/Node.exe -O node
    - name: copy bluemesh.service
      copy:
        src=files/bluemesh.service
        dest=/usr/lib/systemd/system/bluemesh.service
        force=yes
    - name: reload daemon
      command: systemctl daemon-reload
    - name: services enable
      service: name={{item}} enabled=yes
      with_items:
        - bluemesh
    - name: services restart
      service: name={{item}} state=restarted
      with_items:
        - bluemesh
