- git: repo=https://github.com/HackerDom/checksystem.git dest={{cs_dir}}/app

- template: src={{cs_conf}} dest={{cs_dir}}/app/c_s.conf

- file: path={{cs_dir}}/app owner={{cs_user}} group={{cs_user}} recurse=yes

- locale_gen: name={{item}}
  with_items:
    - en_US.UTF-8
    - ru_RU.UTF-8

- command: cpanm --installdeps . chdir={{cs_dir}}/app

- command: /bin/sh -c 'cp {{cs_dir}}/app/etc/systemd/* /etc/systemd/system/'

- template: src=nginx.conf dest=/etc/nginx/sites-available/cs.conf

- file: src=/etc/nginx/sites-available/cs.conf dest=/etc/nginx/sites-enabled/cs.conf state=link

- file: path=/etc/nginx/sites-enabled/default state=absent

- service: name=nginx state=restarted
