[package]
name = "socks"
version = "0.1.0"
authors = ["Nikolay Zhuravlev <znick@znick.ru>"]

[lib]
name = "st"
path = "src/st.rs"

[dependencies]
hyper = "0.8"
stemmer = "*"
rustc-serialize = "*"
regex = "0.1"

[dependencies.urlparse]
version = "0.7.2"
