- apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main 9.5'

- apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc

- apt: name={{item}} state=latest update_cache=yes
  with_items:
    - postgresql-9.5
    - python-psycopg2

- sysctl: name=kernel.sem value='250 32000 32 1024' state=present

- template: src=postgresql.conf.j2 dest=/etc/postgresql/9.5/main/postgresql.conf

- template: src=pg_hba.conf.j2 dest=/etc/postgresql/9.5/main/pg_hba.conf

- service: name=postgresql state=restarted

- postgresql_user: name={{cs_user}} password={{cs_db_pass}} state=present
  sudo: yes
  sudo_user: postgres

- postgresql_db: name=cs_dev owner={{cs_user}} state=present
  sudo: yes
  sudo_user: postgres

- postgresql_db: name=cs_prod owner={{cs_user}} state=present
  sudo: yes
  sudo_user: postgres

#- file: path={{item}} state=directory mode=0755 owner=postgres
#  with_items:
#    - /place/postgresql-backup

#todo: backup db task
#- cron: user="postgres" minute="0" job="..."

