# Ansible >2 deploy playbook
# use: ansible-playbook -i 192.168.0.1, deploy-service.yml
# LOOK AT COMMA, IT IS IMPORTANT     ^^^
# or as usual: ansible-playbook -i hosts.list deploy-service.yml

---
- hosts: all
  remote_user: root
  become_user: root
  become: yes
  tasks:
    - name: install system requiremets
      dnf: name={{item}} disable_gpg_check=yes
      with_items:
        - ruby
        - ruby-devel
        - sqlite-devel
        - libxslt-devel
        - nodejs
    - name: gem install nokogiri/passenger
      gem: state=present name={{item}}
      with_items:
        - nokogiri
        - passenger
        - bundler
    - name: gem install rails
      gem: state=present name=rails version=4.2.1
    - name: add user
      user: name=strongbox shell=/sbin/nologin
    - name: copy project
      copy: src=strongbox dest=/home/ force=yes owner=strongbox
    - set_fact: socks_path="/home/strongbox/tmp/socks"
    - set_fact: app_sock="{{ socks_path }}/app.sock"
    - set_fact: pids_path="/home/strongbox/tmp/pids"
    - set_fact: app_pid="{{ pids_path }}/passenger.pid"
    - name: bundle install
      bundler: state=latest chdir=/home/strongbox executable=/usr/local/bin/bundle
    - name: bundle install
      bundler: state=present user_install=True chdir=/home/strongbox executable=/usr/local/bin/bundle
      become: yes
      become_user: strongbox
    - name: rm tmp
      file: state=absent path=/home/strongbox/tmp
    - name: db:precompile
      shell: "bundle exec rake assets:precompile"
      args:
        chdir: /home/strongbox/
        executable: /bin/bash
      environment:
        RAILS_ENV: production
      become: yes
      become_user: strongbox
      become_method: su
    - name: Ensure sockets directory exists
      file: path={{item}} state=directory owner=strongbox
      with_items:
        - "{{ socks_path }}"
        - "{{ pids_path }}"
    - name: db:migrate
      command: bundle exec rake db:migrate RAILS_ENV=production
      become: yes
      become_user: strongbox
      become_method: su
    - name: run
      shell: "cd /home/strongbox/ && RAILS_ENV=production bundle exec passenger start -d -S {{ app_sock }} --environment production --pid-file {{ app_pid }}"
      become: yes
      become_user: strongbox
      become_method: su
