# Ansible >2 deploy playbook
# use: ansible-playbook -i 192.168.0.1, deploy-service.yml
# LOOK AT COMMA, IT IS IMPORTANT     ^^^
# or as usual: ansible-playbook -i hosts.list deploy-service.yml

---
- hosts: all
  remote_user: root
  become_user: root
  become: yes
  tasks:
    - name: install system requiremets
      dnf: name={{item}} state=latest disable_gpg_check=yes
      with_items:
        - ruby
        - ruby-devel
        - sqlite-devel
        - libxslt-devel
        - nodejs
    - name: gem install nokogiri
      command: gem install nokogiri -- --use-system-libraries
    - name: gem install rails
      command: gem install rails --version 4.2.1
    - name: instal passenger
      command: gem install passenger
    - name: add user
      user: name=strongbox shell=/sbin/nologin
    - name: copy project
      copy: src=strongbox dest=/home/ force=yes owner=strongbox
    - set_fact: socks_path="/home/strongbox/tmp/socks"
    - set_fact: app_sock="{{ socks_path }}/app.sock"
    - set_fact: pids_path="/home/strongbox/tmp/pids"
    - set_fact: app_pid="{{ pids_path }}/passenger.pid"
    - name: bundle update
      shell: "cd /home/strongbox/ && bundle update"
      become: yes
      become_user: strongbox
      become_method: su
    - name: bundle install
      shell: "cd /home/strongbox/ && bundle install"
      become: yes
      become_user: strongbox
      become_method: su
    - name: rm tmp
      shell: "cd /home/strongbox/ && rm -rf tmp"
    - name: db:precompile
      shell: "cd /home/strongbox/ && RAILS_ENV=production bundle exec rake assets:precompile"
      become: yes
      become_user: strongbox
      become_method: su
    - name: Ensure sockets directory exists
      file: path={{ socks_path }} state=directory
      become: yes
      become_user: strongbox
      become_method: su
    - name: Ensure pids directory exists
      file: path={{ pids_path }} state=directory
      become: yes
      become_user: strongbox
      become_method: su
    - name: bundle install
      command: bundle install
      become: yes
      become_user: strongbox
      become_method: su
    - name: db:migrate
      command: bundle exec rake db:migrate RAILS_ENV=production
      become: yes
      become_user: strongbox
      become_method: su
    - name: run
      shell: "cd /home/strongbox/ && RAILS_ENV=production bundle exec passenger start -d -S {{ app_sock }} --environment production --pid-file {{ app_pid }}"
      become: yes
      become_user: strongbox
      become_method: su