- name: stop checkers
  service: name={{item}} state=stopped
  when: mode=="stop" or mode=="resetdb"
  with_items:
    - worker

- name: start checkers
  service: name={{item}} state=started
  when: mode=="start"
  with_items:
    - worker
