- hosts: cs0
  roles: [app]
  vars:
    cs_user: cs
    cs_dir: /home/cs
#   cs_conf: c_s.conf.dev
    cs_conf: c_s.conf.prod
    cs_db_pass: jPcTXXmHIg3RfD2X1706UtXLpUpk2htk
    worker_queues: '-q default'
    worker_jobs: 8
- hosts: cs1
  roles: [app]
  vars:
    cs_user: cs
    cs_dir: /home/cs
#   cs_conf: c_s.conf.dev
    cs_conf: c_s.conf.prod
    cs_db_pass: jPcTXXmHIg3RfD2X1706UtXLpUpk2htk
    worker_queues: '-q checker -q checker-1'
    worker_jobs: 128
- hosts: cs2
  roles: [app]
  vars:
    cs_user: cs
    cs_dir: /home/cs
#   cs_conf: c_s.conf.dev
    cs_conf: c_s.conf.prod
    cs_db_pass: jPcTXXmHIg3RfD2X1706UtXLpUpk2htk
    worker_queues: '-q checker -q checker-2'
    worker_jobs: 48
- hosts: cs3
  roles: [app]
  vars:
    cs_user: cs
    cs_dir: /home/cs
#   cs_conf: c_s.conf.dev
    cs_conf: c_s.conf.prod
    cs_db_pass: jPcTXXmHIg3RfD2X1706UtXLpUpk2htk
    worker_queues: '-q checker -q checker-3'
    worker_jobs: 48
